# Generated by Codex on 2026-04-10

from django.db import migrations


DEFAULT_EMPRESA_GROUP_NAME = "Empresa padrão"


def bootstrap_empresas(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Usuario = apps.get_model("usuarios", "Usuario")

    grupo_padrao, _ = Group.objects.get_or_create(name=DEFAULT_EMPRESA_GROUP_NAME)

    for usuario in Usuario.objects.all():
        if not usuario.groups.exists() and usuario.perfil != "visitante":
            usuario.groups.add(grupo_padrao)


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_alter_usuario_perfil"),
    ]

    operations = [
        migrations.RunPython(bootstrap_empresas, migrations.RunPython.noop),
    ]
