# Generated by Django 6.0.3 on 2026-04-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_bootstrap_empresas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('admin', 'Administrador'), ('orcamentista', 'Editor'), ('visualizador', 'Visualizador'), ('visitante', 'Visitante')], default='orcamentista', max_length=20),
        ),
    ]
