# Generated by Django 6.0.3 on 2026-04-16 16:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=20)),
                ('cor', models.CharField(choices=[('#2563EB', 'Azul'), ('#DC2626', 'Vermelho'), ('#EAB308', 'Amarelo'), ('#16A34A', 'Verde'), ('#EA580C', 'Laranja'), ('#7C3AED', 'Roxo'), ('#DB2777', 'Rosa'), ('#92400E', 'Marrom'), ('#111827', 'Preto'), ('#475569', 'Grafite')], default='#2563EB', max_length=7)),
                ('icone', models.CharField(blank=True, max_length=40)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='financeiro.categoriafinanceira')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_financeiras', to='auth.group')),
            ],
            options={
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('corrente', 'Conta corrente'), ('poupanca', 'Poupança'), ('dinheiro', 'Dinheiro'), ('investimento', 'Investimento'), ('beneficio', 'Benefício'), ('outro', 'Outro')], default='corrente', max_length=20)),
                ('instituicao', models.CharField(blank=True, max_length=120)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('data_saldo_inicial', models.DateField(blank=True, null=True)),
                ('cor', models.CharField(default='#2563EB', max_length=7)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_financeiras', to='auth.group')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('bandeira', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('elo', 'Elo'), ('amex', 'American Express'), ('hipercard', 'Hipercard'), ('outra', 'Outra')], default='outra', max_length=20)),
                ('limite', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('dia_fechamento', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('dia_vencimento', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('cor', models.CharField(default='#111827', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartoes_credito', to='auth.group')),
                ('conta_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartoes', to='financeiro.conta')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MetaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('valor_alvo', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valor_atual_manual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('concluida', 'Concluída'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada')], default='ativa', max_length=20)),
                ('cor', models.CharField(default='#16A34A', max_length=7)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conta_vinculada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='financeiro.conta')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metas_financeiras', to='auth.group')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('ano', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('valor_planejado', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_mensais', to='financeiro.categoriafinanceira')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_mensais', to='auth.group')),
            ],
            options={
                'ordering': ['-ano', '-mes', 'categoria__nome'],
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('transferencia', 'Transferência')], max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('data_competencia', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='financeiro.categoriafinanceira')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='financeiro.conta')),
                ('conta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recebidas', to='financeiro.conta')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes_financeiras_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacoes_financeiras', to='auth.group')),
            ],
            options={
                'ordering': ['-data_competencia', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoriafinanceira',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo', 'nome'), name='categoriafinanceira_empresa_tipo_nome_uniq'),
        ),
        migrations.AddConstraint(
            model_name='conta',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='conta_empresa_nome_uniq'),
        ),
        migrations.AddConstraint(
            model_name='cartaocredito',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='cartaocredito_empresa_nome_uniq'),
        ),
        migrations.AddConstraint(
            model_name='orcamentomensal',
            constraint=models.UniqueConstraint(fields=('empresa', 'ano', 'mes', 'categoria'), name='orcamentomensal_empresa_periodo_categoria_uniq'),
        ),
    ]
