# Generated by Django 6.0.3 on 2026-04-16 17:05

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('ano', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('data_fechamento', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='financeiro.cartaocredito')),
                ('categoria_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faturas_cartao', to='financeiro.categoriafinanceira')),
                ('conta_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faturas_cartao', to='financeiro.conta')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faturas_cartao', to='auth.group')),
                ('transacao_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faturas_cartao_pagas', to='financeiro.transacao')),
            ],
            options={
                'ordering': ['-ano', '-mes', 'cartao__nome'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('data_compra', models.DateField(default=datetime.date.today)),
                ('parcela_numero', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('parcela_total', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('grupo_parcelamento', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.cartaocredito')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_cartao', to='financeiro.categoriafinanceira')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_cartao_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_cartao', to='auth.group')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='financeiro.faturacartao')),
            ],
            options={
                'ordering': ['-data_compra', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='faturacartao',
            constraint=models.UniqueConstraint(fields=('empresa', 'cartao', 'ano', 'mes'), name='faturacartao_empresa_cartao_periodo_uniq'),
        ),
    ]
