# Generated by Django 6.0.3 on 2026-04-16 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('financeiro', '0003_recorrenciafinanceira'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='faturacartao',
            index=models.Index(fields=['empresa', 'status'], name='fatura_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='faturacartao',
            index=models.Index(fields=['empresa', 'ano', 'mes'], name='fatura_emp_periodo_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentocartao',
            index=models.Index(fields=['empresa', 'data_compra'], name='lanc_card_emp_data_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentocartao',
            index=models.Index(fields=['fatura', 'status'], name='lanc_card_fat_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['empresa', 'data_competencia'], name='trans_emp_data_idx'),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['empresa', 'status', 'tipo'], name='trans_emp_stat_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['conta', 'status'], name='trans_conta_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['conta_destino', 'status'], name='trans_dest_stat_idx'),
        ),
    ]
