# Generated by Codex on 2026-04-16

import django.core.validators
import django.db.models.deletion
import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("financeiro", "0004_faturacartao_fatura_empresa_status_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Receita",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao", models.CharField(max_length=255)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("data", models.DateField(default=datetime.date.today)),
                ("categoria", models.CharField(blank=True, max_length=120)),
                ("status", models.CharField(choices=[("recebida", "Recebida"), ("prevista", "Prevista")], default="recebida", max_length=20)),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("criado_por", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="receitas_criadas", to=settings.AUTH_USER_MODEL)),
                ("empresa", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="receitas", to="auth.group")),
            ],
            options={"ordering": ["-data", "-id"]},
        ),
        migrations.CreateModel(
            name="Despesa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao", models.CharField(max_length=255)),
                ("tipo", models.CharField(choices=[("variavel", "Variável"), ("fixa", "Fixa"), ("parcelada", "Parcelada")], default="variavel", max_length=20)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("data", models.DateField(default=datetime.date.today)),
                ("categoria", models.CharField(blank=True, max_length=120)),
                ("parcelas", models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ("status", models.CharField(choices=[("pendente", "Pendente"), ("paga", "Paga"), ("cancelada", "Cancelada")], default="pendente", max_length=20)),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("criado_por", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="despesas_criadas", to=settings.AUTH_USER_MODEL)),
                ("empresa", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="despesas", to="auth.group")),
            ],
            options={"ordering": ["-data", "-id"]},
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=160)),
                ("valor_atual", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))])),
                ("valor_alvo", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))])),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("empresa", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reservas", to="auth.group")),
            ],
            options={"ordering": ["nome"]},
        ),
        migrations.AddIndex(model_name="receita", index=models.Index(fields=["empresa", "data"], name="receita_emp_data_idx")),
        migrations.AddIndex(model_name="receita", index=models.Index(fields=["empresa", "status"], name="receita_emp_status_idx")),
        migrations.AddIndex(model_name="despesa", index=models.Index(fields=["empresa", "data"], name="despesa_emp_data_idx")),
        migrations.AddIndex(model_name="despesa", index=models.Index(fields=["empresa", "status", "tipo"], name="despesa_emp_stat_tipo_idx")),
    ]
