# Generated by Django 6.0.3 on 2026-04-21 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_reserva_criado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartaocredito',
            name='cartaocredito_empresa_nome_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='categoriafinanceira',
            name='categoriafinanceira_empresa_tipo_nome_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='conta',
            name='conta_empresa_nome_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='faturacartao',
            name='faturacartao_empresa_cartao_periodo_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='planejamentomensal',
            name='planejamentomensal_empresa_periodo_categoria_uniq',
        ),
        migrations.RemoveIndex(
            model_name='despesa',
            name='despesa_emp_data_idx',
        ),
        migrations.RemoveIndex(
            model_name='despesa',
            name='despesa_emp_stat_tipo_idx',
        ),
        migrations.RemoveIndex(
            model_name='faturacartao',
            name='fatura_emp_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='faturacartao',
            name='fatura_emp_periodo_idx',
        ),
        migrations.RemoveIndex(
            model_name='lancamentocartao',
            name='lanc_card_emp_data_idx',
        ),
        migrations.RemoveIndex(
            model_name='receita',
            name='receita_emp_data_idx',
        ),
        migrations.RemoveIndex(
            model_name='receita',
            name='receita_emp_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='transacao',
            name='trans_emp_data_idx',
        ),
        migrations.RemoveIndex(
            model_name='transacao',
            name='trans_emp_stat_tipo_idx',
        ),
        migrations.RemoveField(
            model_name='metafinanceira',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='recorrenciafinanceira',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='empresa',
        ),
        migrations.AddIndex(
            model_name='despesa',
            index=models.Index(fields=['criado_por', 'data'], name='despesa_user_data_idx'),
        ),
        migrations.AddIndex(
            model_name='despesa',
            index=models.Index(fields=['criado_por', 'status', 'tipo'], name='despesa_user_stat_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='faturacartao',
            index=models.Index(fields=['status'], name='fatura_status_idx'),
        ),
        migrations.AddIndex(
            model_name='faturacartao',
            index=models.Index(fields=['ano', 'mes'], name='fatura_periodo_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentocartao',
            index=models.Index(fields=['criado_por', 'data_compra'], name='lanc_card_user_data_idx'),
        ),
        migrations.AddIndex(
            model_name='receita',
            index=models.Index(fields=['criado_por', 'data'], name='receita_user_data_idx'),
        ),
        migrations.AddIndex(
            model_name='receita',
            index=models.Index(fields=['criado_por', 'status'], name='receita_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['criado_por', 'data_competencia'], name='trans_user_data_idx'),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['criado_por', 'status', 'tipo'], name='trans_user_stat_tipo_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartaocredito',
            constraint=models.UniqueConstraint(fields=('nome',), name='cartaocredito_nome_uniq'),
        ),
        migrations.AddConstraint(
            model_name='categoriafinanceira',
            constraint=models.UniqueConstraint(fields=('tipo', 'nome'), name='categoriafinanceira_tipo_nome_uniq'),
        ),
        migrations.AddConstraint(
            model_name='conta',
            constraint=models.UniqueConstraint(fields=('nome',), name='conta_nome_uniq'),
        ),
        migrations.AddConstraint(
            model_name='faturacartao',
            constraint=models.UniqueConstraint(fields=('cartao', 'ano', 'mes'), name='faturacartao_cartao_periodo_uniq'),
        ),
        migrations.AddConstraint(
            model_name='planejamentomensal',
            constraint=models.UniqueConstraint(fields=('ano', 'mes', 'categoria'), name='planejamentomensal_periodo_categoria_uniq'),
        ),
        migrations.RemoveField(
            model_name='cartaocredito',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='categoriafinanceira',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='planejamentomensal',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='faturacartao',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='lancamentocartao',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='lancamentocartao',
            name='grupo_parcelamento',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='empresa',
        ),
    ]
