# Generated by Django 6.0.3 on 2026-04-21 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_remove_cartaocredito_cartaocredito_empresa_nome_uniq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentoriaFinanceiraIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('conteudo', models.TextField()),
                ('dados_enviados', models.JSONField(blank=True, default=dict)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorias_financeiras_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['criado_por', '-criado_em'], name='mentoria_user_criado_idx')],
            },
        ),
    ]
