# Generated by Django 6.0.3 on 2026-04-24 21:51

import django.core.validators
from django.db import migrations, models


def preencher_competencia_e_recebimento(apps, schema_editor):
    Receita = apps.get_model("financeiro", "Receita")
    Despesa = apps.get_model("financeiro", "Despesa")

    for receita in Receita.objects.all().iterator():
        update_fields = []
        if not receita.competencia:
            receita.competencia = receita.data
            update_fields.append("competencia")
        if receita.competencia and receita.competencia.day != 1:
            receita.competencia = receita.competencia.replace(day=1)
            if "competencia" not in update_fields:
                update_fields.append("competencia")
        if receita.status == "recebida" and not receita.data_recebimento:
            receita.data_recebimento = receita.data
            update_fields.append("data_recebimento")
        if update_fields:
            receita.save(update_fields=update_fields)

    for despesa in Despesa.objects.all().iterator():
        if not despesa.competencia:
            despesa.competencia = despesa.data
        if despesa.competencia:
            despesa.competencia = despesa.competencia.replace(day=1)
            despesa.save(update_fields=["competencia"])


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_mentoriafinanceiraia'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='competencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='competencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='data_recebimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='parcelas',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='receita',
            name='tipo',
            field=models.CharField(choices=[('variavel', 'Variável'), ('fixa', 'Fixa'), ('parcelada', 'Parcelada')], default='variavel', max_length=20),
        ),
        migrations.RunPython(preencher_competencia_e_recebimento, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='despesa',
            name='competencia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='receita',
            name='competencia',
            field=models.DateField(),
        ),
    ]
