# Generated by Codex on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0009_despesa_competencia_receita_competencia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receita",
            name="ativa",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reserva",
            name="ativa",
            field=models.BooleanField(default=True),
        ),
    ]
