# Generated by Django 6.0.3 on 2026-04-26 21:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_receita_parcela_atual_despesa_parcela_atual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompartilhamentoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('modo_divisao', models.CharField(choices=[('igual', 'Partes iguais'), ('fixo', 'Valores definidos')], default='igual', max_length=20)),
                ('data_prevista_ressarcimento', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compartilhamentos_despesas_criados', to=settings.AUTH_USER_MODEL)),
                ('despesa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamento', to='financeiro.despesa')),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compartilhamentos_despesas_pagador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteCompartilhamentoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado')], default='pendente', max_length=20)),
                ('ressarcimento_confirmado', models.BooleanField(default=False)),
                ('data_aceite', models.DateTimeField(blank=True, null=True)),
                ('data_confirmacao_ressarcimento', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('compartilhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='financeiro.compartilhamentodespesa')),
                ('despesa_gerada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacao_compartilhada', to='financeiro.despesa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compartilhamentos_despesas_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'usuario__username'],
                'indexes': [models.Index(fields=['usuario', 'status'], name='comp_part_user_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('compartilhamento', 'usuario'), name='comp_despesa_usuario_uniq')],
            },
        ),
    ]
