# Generated by Django 6.0.3 on 2026-04-26 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_compartilhamentodespesa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compartilhamentodespesa',
            name='recusado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compartilhamentos_despesas_recusados', to=settings.AUTH_USER_MODEL),
        ),
    ]
