# Generated by Django 6.0.3 on 2026-07-15 15:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_compartilhamentodespesa_recusado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='lancamentocartao',
            name='data_compra',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.CreateModel(
            name='PagamentoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField()),
                ('data_pagamento', models.DateField(default=django.utils.timezone.localdate)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='financeiro.despesa')),
            ],
            options={
                'ordering': ['-competencia'],
                'indexes': [models.Index(fields=['despesa', 'competencia'], name='pag_despesa_comp_idx')],
                'constraints': [models.UniqueConstraint(fields=('despesa', 'competencia'), name='pag_despesa_comp_uniq')],
            },
        ),
        migrations.CreateModel(
            name='RecebimentoReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField()),
                ('data_recebimento', models.DateField(default=django.utils.timezone.localdate)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos', to='financeiro.receita')),
            ],
            options={
                'ordering': ['-competencia'],
                'indexes': [models.Index(fields=['receita', 'competencia'], name='receb_receita_comp_idx')],
                'constraints': [models.UniqueConstraint(fields=('receita', 'competencia'), name='receb_receita_comp_uniq')],
            },
        ),
    ]
