from django.urls import path

from . import views

app_name = "financeiro"

urlpatterns = [
    path("transacoes/", views.transacao_lista, name="transacao_lista"),
    path("transacoes/nova/", views.transacao_criar, name="transacao_criar"),
    path("transacoes/<int:pk>/", views.transacao_visualizar, name="transacao_visualizar"),
    path("transacoes/<int:pk>/editar/", views.transacao_editar, name="transacao_editar"),
    path("transacoes/<int:pk>/excluir/", views.transacao_excluir, name="transacao_excluir"),
    path("transacoes/<int:pk>/pagar/", views.transacao_marcar_pago, name="transacao_marcar_pago"),
    path("contas/", views.conta_lista, name="conta_lista"),
    path("contas/nova/", views.conta_criar, name="conta_criar"),
    path("contas/<int:pk>/", views.conta_visualizar, name="conta_visualizar"),
    path("contas/<int:pk>/editar/", views.conta_editar, name="conta_editar"),
    path("contas/<int:pk>/excluir/", views.conta_excluir, name="conta_excluir"),
    path("contas/<int:pk>/extrato/", views.conta_extrato, name="conta_extrato"),
    path("categorias/", views.categoria_lista, name="categoria_lista"),
    path("categorias/nova/", views.categoria_criar, name="categoria_criar"),
    path("categorias/<int:pk>/", views.categoria_visualizar, name="categoria_visualizar"),
    path("categorias/<int:pk>/editar/", views.categoria_editar, name="categoria_editar"),
    path("categorias/<int:pk>/excluir/", views.categoria_excluir, name="categoria_excluir"),
    path("cartoes/", views.cartao_lista, name="cartao_lista"),
    path("cartoes/novo/", views.cartao_criar, name="cartao_criar"),
    path("cartoes/compras/nova/", views.compra_cartao_criar, name="compra_cartao_criar"),
    path("cartoes/<int:pk>/", views.cartao_visualizar, name="cartao_visualizar"),
    path("cartoes/<int:pk>/editar/", views.cartao_editar, name="cartao_editar"),
    path("cartoes/<int:pk>/excluir/", views.cartao_excluir, name="cartao_excluir"),
    path("faturas/", views.fatura_lista, name="fatura_lista"),
    path("faturas/nova/", views.fatura_criar, name="fatura_criar"),
    path("faturas/<int:pk>/", views.fatura_visualizar, name="fatura_visualizar"),
    path("faturas/<int:pk>/editar/", views.fatura_editar, name="fatura_editar"),
    path("faturas/<int:pk>/pagar/", views.fatura_pagar, name="fatura_pagar"),
    path("lancamentos-cartao/<int:pk>/cancelar/", views.lancamento_cartao_cancelar, name="lancamento_cartao_cancelar"),
    path("relatorios/fluxo-caixa/", views.relatorio_fluxo_caixa, name="relatorio_fluxo_caixa"),
    path("planejamento/", views.planejamento_lista, name="planejamento_lista"),
    path("planejamento/novo/", views.planejamento_criar, name="planejamento_criar"),
    path("planejamento/<int:pk>/editar/", views.planejamento_editar, name="planejamento_editar"),
    path("metas/", views.meta_lista, name="meta_lista"),
    path("metas/nova/", views.meta_criar, name="meta_criar"),
    path("metas/<int:pk>/editar/", views.meta_editar, name="meta_editar"),
    path("recorrencias/", views.recorrencia_lista, name="recorrencia_lista"),
    path("recorrencias/nova/", views.recorrencia_criar, name="recorrencia_criar"),
    path("recorrencias/<int:pk>/editar/", views.recorrencia_editar, name="recorrencia_editar"),
    path("recorrencias/<int:pk>/gerar/", views.recorrencia_gerar, name="recorrencia_gerar"),
]
